#!/usr/bin/env python3
"""
Server DBC Install Script

Merges custom DBC entries into existing server DBC files.
Generated by the build system.

This script reads custom-only DBC files from the custom_dbc/ directory
and merges their records into the target server's existing DBC files.
Base entries are NEVER modified -- only custom records are appended.

String-bearing DBCs (SkillLine, Faction, SpellItemEnchantment, Spell)
have their string offsets automatically remapped during the merge.

Usage:
    python install_server_dbc.py <server_dbc_directory>

Example:
    python install_server_dbc.py <path_to_server>\dbc
"""

import struct
import sys
import os
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: pip install pyyaml")
    sys.exit(1)


DBC_MAGIC = b'WDBC'

# Fields that contain string block offsets for each DBC type.
# WotLK 3.3.5a: locale strings use 16 consecutive uint32 fields.
# DBCs not listed here have no string fields (all uint32 integers).
STRING_FIELDS = {
    'SkillLine.dbc': list(range(3, 19)) + list(range(20, 36)) + list(range(38, 54)),
    'Faction.dbc': list(range(23, 39)) + list(range(40, 56)),
    'SpellItemEnchantment.dbc': list(range(14, 30)),
    'Spell.dbc': (list(range(136, 152)) + list(range(153, 169))
                  + list(range(170, 186)) + list(range(187, 203))),
}


def read_dbc_file(filepath):
    """Read a DBC file and return header info, raw records, and string block."""
    with open(filepath, 'rb') as f:
        magic = f.read(4)
        if magic != DBC_MAGIC:
            raise ValueError(f"Invalid DBC magic in {filepath}: {magic}")

        record_count, field_count, record_size, string_block_size = (
            struct.unpack('<4I', f.read(16)))

        records = []
        for _ in range(record_count):
            records.append(f.read(record_size))

        string_block = f.read(string_block_size)

    return {
        'record_count': record_count,
        'field_count': field_count,
        'record_size': record_size,
        'string_block_size': string_block_size,
    }, records, string_block


def write_dbc_file(filepath, header, records, string_block):
    """Write a DBC file."""
    with open(filepath, 'wb') as f:
        f.write(DBC_MAGIC)
        f.write(struct.pack('<I', len(records)))
        f.write(struct.pack('<I', header['field_count']))
        f.write(struct.pack('<I', header['record_size']))
        f.write(struct.pack('<I', len(string_block)))

        for record in records:
            f.write(record)

        f.write(string_block)


def install_dbc_entries(target_dbc_path, custom_dbc_path, dbc_filename):
    """
    Merge custom records from a custom-only DBC into a target server DBC.

    Custom records are appended to the target. Records whose IDs already
    exist in the target are skipped (idempotent install). String offsets
    in custom records are remapped to account for the combined string block.

    Args:
        target_dbc_path: Path to the server's existing DBC file
        custom_dbc_path: Path to the custom-only DBC file
        dbc_filename: Filename (for STRING_FIELDS lookup)

    Returns:
        Number of entries added
    """
    if not os.path.exists(target_dbc_path):
        print(f"  Warning: {dbc_filename} not found at {target_dbc_path}")
        print(f"  Copying custom DBC as-is (no base to merge with)")
        import shutil
        shutil.copy2(str(custom_dbc_path), str(target_dbc_path))
        header, records, _ = read_dbc_file(custom_dbc_path)
        return len(records)

    # Read target (server's existing DBC)
    target_header, target_records, target_strings = read_dbc_file(target_dbc_path)

    # Read custom-only DBC
    custom_header, custom_records, custom_strings = read_dbc_file(custom_dbc_path)

    if target_header['record_size'] != custom_header['record_size']:
        print(f"  ERROR: Record size mismatch for {dbc_filename}: "
              f"target={target_header['record_size']}, "
              f"custom={custom_header['record_size']}")
        return 0

    record_size = target_header['record_size']
    fields_per_record = record_size // 4

    # Build set of existing IDs in target
    existing_ids = set()
    for record in target_records:
        record_id = struct.unpack('<I', record[:4])[0]
        existing_ids.add(record_id)

    # Get string field indices for this DBC type
    string_fields = STRING_FIELDS.get(dbc_filename, [])
    target_string_len = len(target_strings)

    added = 0
    new_records = list(target_records)

    for record in custom_records:
        record_id = struct.unpack('<I', record[:4])[0]
        if record_id in existing_ids:
            continue  # Skip -- already installed or native entry

        # Remap string offsets: custom record offsets reference custom_strings,
        # but in the merged file they need to reference
        # target_strings + custom_strings (concatenated).
        # New offset = old offset + len(target_strings)
        if string_fields:
            fields = list(struct.unpack(f'<{fields_per_record}I', record))
            for fi in string_fields:
                if fi < fields_per_record and fields[fi] != 0:
                    fields[fi] += target_string_len
            record = struct.pack(f'<{fields_per_record}I', *fields)

        new_records.append(record)
        added += 1

    if added > 0:
        # Combine string blocks: target's original + our custom strings
        merged_strings = target_strings + custom_strings
        write_dbc_file(target_dbc_path, target_header, new_records, merged_strings)
        print(f"  {dbc_filename}: added {added} custom entries "
              f"({len(target_records)} -> {len(new_records)} records)")
    else:
        print(f"  {dbc_filename}: all custom entries already present")

    return added


def main():
    if len(sys.argv) < 2:
        print("Usage: python install_server_dbc.py <server_dbc_directory>")
        print("Example: python install_server_dbc.py "
              "K:\\TrinityCore\\Build\\bin\\RelWithDebInfo\\dbc")
        sys.exit(1)

    target_dbc_dir = Path(sys.argv[1])

    if not target_dbc_dir.exists():
        print(f"ERROR: Target DBC directory does not exist: {target_dbc_dir}")
        sys.exit(1)

    # Load manifest from same directory as this script
    script_dir = Path(__file__).parent
    manifest_path = script_dir / 'id_manifest.yaml'

    if not manifest_path.exists():
        print(f"ERROR: id_manifest.yaml not found at {manifest_path}")
        sys.exit(1)

    print(f"Loading manifest from {manifest_path}...")
    with open(manifest_path, 'r', encoding='utf-8') as f:
        manifest = yaml.safe_load(f)

    dbc_entries = manifest.get('dbc_entries', {})

    if not dbc_entries:
        print("No dbc_entries found in manifest. Nothing to install.")
        return

    custom_dbc_dir = script_dir / 'custom_dbc'
    if not custom_dbc_dir.exists():
        print(f"ERROR: custom_dbc/ directory not found at {custom_dbc_dir}")
        print("The custom_dbc/ folder should be in the same directory as this script.")
        sys.exit(1)

    print(f"\nInstalling custom DBC entries into {target_dbc_dir}...")
    total_added = 0

    for dbc_filename in sorted(dbc_entries.keys()):
        custom_ids = dbc_entries[dbc_filename]
        if not custom_ids:
            continue

        custom_dbc_path = custom_dbc_dir / dbc_filename
        if not custom_dbc_path.exists():
            print(f"  Warning: {dbc_filename} not found in custom_dbc/, skipping")
            continue

        print(f"  {dbc_filename}: {len(custom_ids)} custom entries to install")
        target_path = target_dbc_dir / dbc_filename
        added = install_dbc_entries(target_path, custom_dbc_path, dbc_filename)
        total_added += added

    print(f"\nInstall complete. Added {total_added} total entries "
          f"across {len(dbc_entries)} DBC files.")
    print("\nRestart your worldserver for changes to take effect.")


if __name__ == '__main__':
    main()
