#!/usr/bin/env python3
"""
Server DBC Uninstall Script

Removes custom entries from server DBC files.
Generated by World of Stonecraft build system.

This script is generic and manifest-driven. It reads dbc_entries from
id_manifest.yaml and removes exactly those IDs from each DBC file.
All DBC formats use field 0 as the record ID (uint32), so one removal
function handles every DBC type.

Usage:
    python uninstall_server_dbc.py <server_dbc_directory>

Example:
    python uninstall_server_dbc.py <path_to_server>\dbc
"""

import struct
import sys
import os
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: pip install pyyaml")
    sys.exit(1)


DBC_MAGIC = b'WDBC'


def read_dbc_file(filepath):
    """Read a DBC file and return header info and raw records."""
    with open(filepath, 'rb') as f:
        magic = f.read(4)
        if magic != DBC_MAGIC:
            raise ValueError(f"Invalid DBC magic in {filepath}: {magic}")

        record_count, field_count, record_size, string_block_size = struct.unpack('<4I', f.read(16))

        records = []
        for _ in range(record_count):
            records.append(f.read(record_size))

        string_block = f.read(string_block_size)

    return {
        'record_count': record_count,
        'field_count': field_count,
        'record_size': record_size,
        'string_block_size': string_block_size,
    }, records, string_block


def write_dbc_file(filepath, header, records, string_block):
    """Write a DBC file."""
    with open(filepath, 'wb') as f:
        f.write(DBC_MAGIC)
        f.write(struct.pack('<I', len(records)))
        f.write(struct.pack('<I', header['field_count']))
        f.write(struct.pack('<I', header['record_size']))
        f.write(struct.pack('<I', len(string_block)))

        for record in records:
            f.write(record)

        f.write(string_block)


def remove_dbc_entries(dbc_path, ids_to_remove):
    """
    Remove records by ID from any DBC file.

    All WotLK DBC formats have field 0 as the record ID (uint32).
    This function works for every DBC type.

    Args:
        dbc_path: Path to the DBC file
        ids_to_remove: Set of integer IDs to remove

    Returns:
        Number of entries removed
    """
    if not os.path.exists(dbc_path):
        return 0

    dbc_name = os.path.basename(dbc_path)
    print(f"  Reading {dbc_name}...")
    header, records, string_block = read_dbc_file(dbc_path)

    original_count = len(records)
    filtered_records = []
    removed_count = 0

    for record in records:
        record_id = struct.unpack('<I', record[:4])[0]
        if record_id in ids_to_remove:
            removed_count += 1
        else:
            filtered_records.append(record)

    if removed_count > 0:
        print(f"  {dbc_name}: removed {removed_count} entries ({original_count} -> {len(filtered_records)})")
        write_dbc_file(dbc_path, header, filtered_records, string_block)
    else:
        print(f"  {dbc_name}: no matching entries found")

    return removed_count


def main():
    if len(sys.argv) < 2:
        print("Usage: python uninstall_server_dbc.py <server_dbc_directory>")
        print("Example: python uninstall_server_dbc.py K:\\TrinityCore\\Build\\bin\\RelWithDebInfo\\dbc")
        sys.exit(1)

    target_dbc_dir = Path(sys.argv[1])

    if not target_dbc_dir.exists():
        print(f"ERROR: Target DBC directory does not exist: {target_dbc_dir}")
        sys.exit(1)

    # Load manifest from same directory as this script
    script_dir = Path(__file__).parent
    manifest_path = script_dir / 'id_manifest.yaml'

    if not manifest_path.exists():
        print(f"ERROR: id_manifest.yaml not found at {manifest_path}")
        sys.exit(1)

    print(f"Loading manifest from {manifest_path}...")
    with open(manifest_path, 'r', encoding='utf-8') as f:
        manifest = yaml.safe_load(f)

    dbc_entries = manifest.get('dbc_entries', {})

    if not dbc_entries:
        print("No dbc_entries found in manifest. Nothing to uninstall.")
        return

    total_removed = 0

    for dbc_filename, custom_ids in sorted(dbc_entries.items()):
        if not custom_ids:
            continue
        ids_to_remove = set(int(i) for i in custom_ids)
        print(f"  {dbc_filename}: {len(ids_to_remove)} custom IDs to remove")
        dbc_path = target_dbc_dir / dbc_filename
        removed = remove_dbc_entries(dbc_path, ids_to_remove)
        total_removed += removed

    print(f"\nUninstall complete. Removed {total_removed} total entries from {len(dbc_entries)} DBC files.")


if __name__ == '__main__':
    main()
