-- Skill Jewels: show spell tooltip alongside item tooltip for Skill Jewel gems.
-- Data loaded from SkillJewelsData.lua (generated by prebuild).

local SpellTip = CreateFrame("GameTooltip", "SkillJewelSpellTooltip", UIParent, "GameTooltipTemplate")

local function ShowSpellTooltip(itemId)
    local data = SkillJewelsData and SkillJewelsData[itemId]
    if not data or #data == 0 then return end

    local spellId = nil

    if data[1] < 0 then
        -- Multi-spell gem: negative IDs, show first spell
        spellId = -data[1]
    else
        -- Rank-chain gem: pairs of (spell, level)
        local playerLevel = UnitLevel("player")
        for i = 1, #data, 2 do
            local spell = data[i]
            local level = data[i + 1]
            if playerLevel >= level then
                spellId = spell
            end
        end
    end

    if not spellId then return end

    SpellTip:SetOwner(GameTooltip, "ANCHOR_NONE")
    SpellTip:SetPoint("TOPLEFT", GameTooltip, "BOTTOMLEFT", 0, 0)
    SpellTip:SetHyperlink("spell:" .. spellId)
    SpellTip:Show()
end

GameTooltip:HookScript("OnTooltipSetItem", function(self)
    local _, link = self:GetItem()
    if not link then return end
    local itemId = tonumber(link:match("item:(%d+)"))
    if itemId then
        ShowSpellTooltip(itemId)
    end
end)

GameTooltip:HookScript("OnHide", function()
    SpellTip:Hide()
end)
